const { time } = require('console');
let database = require('./database/userDocConnection');


//Receives form data, creates object mirroring database schema, 
const createUser = (req) => {
    try {
        let data = req.body;

        let user = {
            id: null, //to be autogenerated and assigned. ToDo: determine if this should be done here or in databse insertion
            firstName: data.firstName,
            lastName: data.lastName,
            email: data.email,
            postcode: data.postcode,
            profile: null
        };

        
        let flag = database.insertUser(user);

        return flag;
        
    }
    catch{
        return false;
    }
}


//Currently (16/09/2021), it is assumed a user document can be deleted with only id.
const deleteUser = (req) => {
    try {
        let data = req.body;
        let flag = database.DeleteUser(data.id);
        
        return flag;
    }
    catch {
        return false;
    }
}


const getUser = (req) => {
    try{

        /*By not converting the request body into a user document format, and only passing the forwarding the given argument (req.body), the decision as to what specific information
        is required to retrieve a user can be determined at a later time. Therefore, the only restriction is that the argument is sufficient to locate a document in the collection.*/
        let user = req.body;
        let flag = database.deleteUser(user);

        return flag;
        
    }
    catch {
        return false;
    }
}


const updateUser = (req) => {
}


module.exports = {createUser, deleteUser, getUser, updateUser}