let database = require('./database/userDocConnection');


//Receives form data, creates object mirroring database schema, 
const createUser = (req) => {
    try {
        let data = req.body;

        let user = {
            id: null, //to be autogenerated and assigned. ToDo: determine if this should be done here or in databse insertion
            firstName: data.firstName,
            lastName: data.lastName,
            email: data.email,
            postcode: data.postcode,
            profile: null
        };

        
        let flag = database.insertUser(user);

        return flag;
        
    }
    catch{
        return false;
    }
}


//Currently (16/09/2021), it is assumed a user document can be deleted with only id.
const deleteUser = (req) => {
    try {
        let data = req.body;
        let flag = database.DeleteUser(data.id);
        
        return flag;
    }
    catch {
        return false;
    }
}


const getUser = (req) => {}


const updateUser = (req) => {
}


module.exports = {createUser, deleteUser, getUser, updateUser}